{
    "openapi": "3.1.1",
    "info": {
        "title": "Бронирование отелей",
        "description": "Бронирование отелей, глэмпингов и аппартаментов",
        "version": "1.4.1"
    },
    "servers": [
        {
            "url": "https://api.hotels.com/v1",
            "description": "Рабочий сервер"
        },
        {
            "url": "https://test-api.hotels.com",
            "description": "Тестовый сервер"
        }
    ],
    "components": {
        "parameters": {
            "hotelID": {
                "name": "hotelID",
                "description": "Идентификатор выбранного отеля",
                "in": "path",
                "required": true,
                "schema": {
                    "type": "integer",
                    "format": "int64",
                    "minimum": 1,
                    "default": 1
                },
                "example": 75
            },
            "roomID": {
                "name": "roomID",
                "description": "Идентификатор выбранного номера в отеле",
                "in": "path",
                "required": true,
                "schema": {
                    "type": "integer",
                    "format": "int64",
                    "minimum": 1,
                    "default": 1
                },
                "example": 65
            },
            "orderID": {
                "name": "orderID",
                "description": "Идентификатор выбранного бронирования номера",
                "in": "path",
                "required": true,
                "schema": {
                    "type": "integer",
                    "format": "int64",
                    "minimum": 1,
                    "default": 1
                },
                "example": 435
            },
            "clientID": {
                "name": "clientID",
                "description": "Идентификатор выбранного клиента",
                "in": "path",
                "required": true,
                "schema": {
                    "type": "integer",
                    "format": "int64",
                    "minimum": 1,
                    "default": 1
                },
                "example": 14
            },
            "offsetParam": {
                "name": "offset",
                "description": "Номер первого элемента на странице",
                "in": "query",
                "required": false,
                "schema": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                }
            },
            "limitParam": {
                "name": "limit",
                "description": "Количество элементов на странице",
                "in": "query",
                "required": false,
                "schema": {
                    "type": "integer",
                    "minimum": 10,
                    "maximum": 100,
                    "default": 20
                }
            }
        },
        "schemas": {
            "Hotel": {
                "type": "object",
                "required": [
                    "id",
                    "name",
                    "image",
                    "description",
                    "feedback"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "default": 1,
                        "description": "Идентификатор отеля"
                    },
                    "name": {
                        "type": "string",
                        "minLength": 10,
                        "maxLength": 200,
                        "description": "Полное наименование отеля"
                    },
                    "image": {
                        "type": "string",
                        "minLength": 5,
                        "maxLength": 1000,
                        "description": "Изображение отеля (URL)"
                    },
                    "description": {
                        "type": "string",
                        "minLength": 100,
                        "maxLength": 1000,
                        "description": "Полное описание отеля"
                    },
                    "feedback": {
                        "type": "string",
                        "enum": [
                            "Ниже ожидаемого",
                            "Совпадает с ожиданием",
                            "Выше ожидаемого"
                        ],
                        "description": "Обратная связь от гостей"
                    },
                    "rooms": {
                        "type": "array",
                        "minItems": 10,
                        "maxItems": 200,
                        "description": "Список доступных номеров"
                    }
                },
                "example": {
                    "id": 412,
                    "name": "Отель 'Престиж'",
                    "image": "https://example.com/images/hotel-prestige.jpg",
                    "description": "Роскошный пятизвездочный отель в самом сердце Москвы с видом на Красную площадь",
                    "feedback": "Выше ожидаемого",
                    "rooms": [101, 102, 103, 206, 204, 202]
                }
            },
            "Room": {
                "type": "object",
                "required": [
                    "id",
                    "name",
                    "isAvailable",
                    "hotelID"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "default": 1,
                        "description": "Идентификатор номера отеля"
                    },
                    "name": {
                        "oneOf": [
                            {
                                "type": "string",
                                "minLength": 1
                            },
                            {
                                "type": "integer",
                                "format": "int64",
                                "minimum": 1
                            }
                        ],
                        "description": "Наименование номера отеля"
                    },
                    "isAvailable": {
                        "type": "boolean",
                        "description": "Статус выбранного номера"
                    },
                    "hotelID": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "default": 1,
                        "description": "Идентификатор отеля"
                    }
                },
                "example": {
                    "id": 615,
                    "name": "Люкс с видом на собор",
                    "isAvailable": true,
                    "hotelID": 412
                }
            },
            "Order": {
                "type": "object",
                "required": [
                    "id",
                    "roomID",
                    "clientID",
                    "dateTime"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "default": 1,
                        "description": "Идентификатор записи о бронировании номера в отеле"
                    },
                    "roomID": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "default": 1,
                        "description": "Идентификатор номера в отеле"
                    },
                    "clientID": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "default": 1,
                        "description": "Идентификатор клиента"
                    },
                    "dateTime": {
                        "type": "string",
                        "format": "date-time",
                        "description": "Дата и время выполнения бронирования"
                    }
                },
                "example": {
                    "id": 1521,
                    "roomID": 615,
                    "clientID": 412,
                    "dateTime": "2025-01-15T14:00:00Z"
                }
            },
            "Client": {
                "type": "object",
                "required": [
                    "id",
                    "name",
                    "surname",
                    "patronymic",
                    "passport",
                    "phoneNumber"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "description": "Идентификатор клиента"
                    },
                    "name": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 50,
                        "description": "Полное имя клиента"
                    },
                    "surname": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 100,
                        "description": "Полная фамилия клиента"
                    },
                    "patronymic": {
                        "type": "string",
                        "minLength": 5,
                        "maxLength": 100,
                        "description": "Полное отчество клиента"
                    },
                    "passport": {
                        "type": "string",
                        "pattern": "^[0-9]{10}$",
                        "description": "Серия и номер паспорта РФ клиента"
                    },
                    "phoneNumber": {
                        "type": "string",
                        "pattern": "^\\+7\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$",
                        "description": "Номер телефона клиента"
                    }
                },
                "example": {
                    "id": 362,
                    "name": "Иван",
                    "surname": "Иванов",
                    "patronymic": "Иванович",
                    "passport": "4510123456",
                    "phoneNumber": "+7(495)123-45-67"
                }
            },
            "Error": {
                "type": "object",
                "required": [
                    "message"
                ],
                "properties": {
                    "message": {
                        "type": "string",
                        "description": "Человекочитаемое сообщение об ошибке",
                        "minLength": 10,
                        "maxLength": 500
                    },
                    "errorCode": {
                        "type": "string",
                        "description": "Машинночитаемый код ошибки",
                        "minLength": 5,
                        "maxLength": 25
                    }
                }
            }
        }
    },
    "paths": {
        "/hotels": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/offsetParam"
                    },
                    {
                        "$ref": "#/components/parameters/limitParam"
                    }
                ],
                "summary": "Просмотр полного списка отелей",
                "description": "Возвращает полный список всех доступных для бронирования отелей",
                "tags": [
                    "Поиск отеля для бронирования номера"
                ],
                "operationId": "getHotels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Hotel"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/hotels/{hotelID}": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/hotelID"
                    }
                ],
                "summary": "Получить информацию об определенном отеле",
                "description": "Возвращает полную информацию об отеле по его уникальному идентификатору",
                "operationId": "getHotelByID",
                "tags": [
                    "Просмотр информации по выбранному отелю"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Hotel"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Отель с указанным ID не найден",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rooms": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/offsetParam"
                    },
                    {
                        "$ref": "#/components/parameters/limitParam"
                    }
                ],
                "summary": "Получить список номеров",
                "description": "Возвращает полный список номеров с подробной информацией о каждом из них",
                "operationId": "getRooms",
                "tags": [
                    "Поиск номера в отеле для бронирования"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Room"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rooms/{roomID}": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/roomID"
                    }
                ],
                "summary": "Получить информацию об определенном номере",
                "description": "Возвращает полную информацию о номере по его уникальному идентификатору",
                "operationId": "getRoomByID",
                "tags": [
                    "Просмотр информации по определенному номеру"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Room"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Номер с указанным ID не найден",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/offsetParam"
                    },
                    {
                        "$ref": "#/components/parameters/limitParam"
                    }
                ],
                "summary": "Получить список бронирований",
                "description": "Возвращает полный список всех бронирований",
                "operationId": "getOrders",
                "tags": [
                    "Бронирование номера в отеле"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Order"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Забронировать номер",
                "description": "Забронировать выбранный номер в отеле",
                "tags": [
                    "Бронирование номера в отеле"
                ],
                "operationId": "createOrder",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Order"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Бронирование успешно создано",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Связанный ресурс не найден",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Конфликт",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/orders/{orderID}": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/orderID"
                    }
                ],
                "summary": "Получить информацию об определенном бронировании",
                "description": "Возвращает полную информацию о конкретном бронировании по его уникальному идентификатору",
                "operationId": "getOrderByID",
                "tags": [
                    "Просмотр информации по выбранному бронированию"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Запись о бронировании с таким ID не найдена",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/offsetParam"
                    },
                    {
                        "$ref": "#/components/parameters/limitParam"
                    }
                ],
                "summary": "Получить список клиентов",
                "description": "Возвращает полный список всех клиентов",
                "operationId": "getClients",
                "tags": [
                    "Просмотр информации о всех клиентах"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Client"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Создать клиента",
                "description": "Создать запись о клиенте",
                "tags": [
                    "Создание клиента"
                ],
                "operationId": "createClient",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Client"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Клиент успешно создан",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Client"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Конфликт",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/clients/{clientID}": {
            "get": {
                "parameters": [
                    {
                        "$ref": "#/components/parameters/clientID"
                    }
                ],
                "summary": "Получить информацию об определенном клиенте",
                "description": "Возвращает полную информацию о конкретном клиенте по его уникальному идентификатору",
                "operationId": "getClientByID",
                "tags": [
                    "Просмотр информации по выбранному клиенту"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Client"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Клиент с таким ID не найден",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Сервис временно недоступен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}